---
title: "Galamsey Detection"
author: "Kalong Boniface"
output: html_document
date: '2022-03-24'
---

```{r setup, include=FALSE,message=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(reticulate)
library(cptcity)
library(raster)
library(stars)
library(rgee)
library(sits)
library(reshape2)
library(ggplot2)
library(sf)
library(googleCloudStorageR)


# library(dygraphs)
# dygraph(nhtemp) %>% 
#   dyRangeSelector

# knitr::kable(head(ggplot2::diamonds))
```


```{r}
ee_Initialize( drive = TRUE)

```

# Loading and Filtering SENTINEL 1 Collection

```{r}
Map$setCenter(-2.063,6.088,12)
geom <- ee$Geometry$Polygon(coords = list(
  c(8.1462, 1.1591),
  c(88.1462, -3.4497),
  c(4.1766, -3.4497),
  c(4.1766, 1.591)
  ),
   proj = "EPSG:4326",
  geodesic = TRUE
)
sentenil1 <- ee$ImageCollection('sentenl1')$
  filterBounds(geom)$
  filterDate('2010-01-01', '2022-01-01')$
  filter(ee$Filter$listContains('transmitterReceiverPolarisation', 'VV'))$
  filter(ee$Filter$listContains('transmitterReceiverPolarisation', 'VH'))$
  #Filter to get images collected in interferometric wide swath mode.
  filter(ee$Filter$eq('instrumentMode', 'IW'))$
  filter(ee$Filter$eq('orbitProperties_pass', 'ASCENDING'));
```


```{r}
print(sentenil1)
```
# Quaterlly 
```{r}
#Year 2010
# First Quarter 
s12010Q1 = sentenil1$filter(ee$Filter$calendarRange(2010,2010,'year'))$
                             filter(ee$Filter$calendarRange(1,3,'month'))$
                             mean()$
                             clip(geom)$
                             set('date', ee$Date$fromYMD(2010,1,1));
print(s12010Q1)

# Second Quarter 
s12010Q1 = sentenil1$filter(ee$Filter$calendarRange(2010,2010,'year'))$
                             filter(ee$Filter$calendarRange(4,6,'month'))$
                             mean()$
                             clip(geom)$
                             set('date', ee$Date$fromYMD(2010,4,1));
print(s12010Q1)

# Third Quarter 
s12010Q1 = sentenil1$filter(ee$Filter$calendarRange(2010,2010,'year'))$
                             filter(ee$Filter$calendarRange(7,9,'month'))$
                             mean()$
                             clip(geom)$
                             set('date', ee$Date$fromYMD(2010,7,1));
print(s12010Q1)

# Fouth Quarter 
s12010Q1 = sentenil1$filter(ee$Filter$calendarRange(2010,2010,'year'))$
                             filter(ee$Filter$calendarRange(10,12,'month'))$
                             mean()$
                             clip(geom)$
                             set('date', ee$Date$fromYMD(2010,10,1));
print(s12010Q1)
```



```{r}
s1QuarterlyCollection = ee$ImageCollection([
  
])
```


