---
title: "Untitled"
author: "Boniface Kalong"
date: "7/5/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
library(cptcity)
library(raster)
library(stars)
library(rgee)
library(sits)
library(reshape2)
library(ggplot2)
#library(gganimate)
library(sf)
#library(googleCloudStorageR)
ee_Initialize( drive = TRUE)
```

```{r}
# initialize GEE, this will have you log in to Google Drive
ee_check() # Check non-R dependencies
#ee_clean_pyenv() # Remove reticulate system variables
ee$String('Hello World from EE!')$getInfo()
```


```{r}
Map$setCenter(-2.063,6.088,12)
geometry <- ee$Geometry$Polygon(coords = list(
  c(-2.090671121147858, 6.238499750885412),
  c(-2.090671121147858, 5.861583229053705),
  c(-1.634738503960358, 5.861583229053705),
  c(-1.634738503960358, 6.238499750885412)
  ),
   proj = "EPSG:4326",
  geodesic = TRUE
)
```


```{r}
# Import the example feature collection and subset the forest feature$
 NDVI = ee$ImageCollection('COPERNICUS/S2_SR')$
               filter(ee$Filter$eq('label', 'Forest'))$
               filterDate('2000-01-01', '2022-01-01')$
               select('NDVI')
EVI = ee$FeatureCollection('')$
               filter(ee$Filter$eq('label', 'Forest'))$
               filterDate('2000-01-01', '2022-01-01')$
               select( 'EVI')
               
```
# 2
```{r}
  scale_and_rename_NDVI <- function(image){
    Date_N <- ee$Date(image$get("system:time_start"))$format('YYYY_MM_dd')
     
    return(image$multiply(0.0001)$select('NDVI')$rename(Date_N))
  }

scale_and_rename_EVI <- function(image){
    Date_E <- ee$Date(image$get("system:time_start"))$format('YYYY_MM_dd')
     
    return(image$multiply(0.0001)$select( 'EVI')$rename(Date_E))
  }
```

# 3

```{r}
scale_ndvi_and_NDVI <- NDVI$map(scale_and_rename_NDVI)
scale_ndvi_and_EVI <- NDVI$map(scale_and_rename_EVI)
```


# 4
```{r}
Test_site <- ee$Geometry$Point(c(-1.86,6.05))
```

# 5
```{r}

setwd("C:/Users/Guy/Documents/GitHub/Artisanal-Mining-In-Ghana-Galamsey/Ghana/New Regions")
roi <- st_read("New_Regions.shp",
                stringsAsFactors = FALSE,
                quiet = TRUE
                )
```
# 6
```{r}

NDVI_at_Point <- ee_extract(scale_ndvi_and_EVI,Test_site, sf = FALSE)
NDVI_at_Point
```

```{r}
# Define the chart and print it to the console$
 chart =
    ui$Chart$image$
     series({
          imageCollection: vegIndices,
          region: geometry,
          reducer: ee$Reducer$mean(),
          scale: 500,
          xProperty: 'system:time_start'
        })$
      setSeriesNames[['EVI', 'NDVI']]$
      setOptions({
          title: 'Average Vegetation Index Value by Date for Forest',
          hAxis: {title: 'Date', titleTextStyle: {italic: false, bold: true}},
          vAxis: {
            title: 'Vegetation index (x1e4)',
            titleTextStyle: {italic: false, bold: true}
          },
          lineWidth: 5,
          colors: ['e37d05', '1d6b99'],
          curveType: 'function'
        });
print(chart);
```

